<a href="https://colab.research.google.com/github/Sisg2408/Sisg2408/blob/main/Copy_of_Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [ ]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [8]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
print(distance_array)

[  100   200   400   800  1500  3000  5000 10000]


3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [10]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
print(np.min(distance_array))
print(np.max(distance_array))

100
10000


4) To find the average distance, use the np.mean() function



In [11]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
print(np.mean(distance_array))

2625.0


5) use the np.sum() function to find the total distance

In [12]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
print(sum(distance_array))

21000


6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [16]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
print(np.cumsum(distance_array))

[  100   300   700  1500  3000  6000 11000 21000]


7) To round all of the values in an array, use np.round()

In [15]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
print(np.round(distance_array))

[  100   200   400   800  1500  3000  5000 10000]


8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [ ]:
import numpy as np
time = [10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45]
type(time)
time_array = np.array(time)

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [17]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
time = [10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45]
type(time)
time_array = np.array(time)
print(distance_array/time_array)

[9.41619586 9.37207123 8.29015544 7.0528079  6.41135237 5.92265019
 5.77253888 5.69006231]


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [19]:
import numpy as np
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]
type(distance)
distance_array = np.array(distance)
time = [10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45]
type(time)
time_array = np.array(time)
Dato = distance_array/time_array*0.00062*3600
type(Dato)
dato_array = np.array(Dato)
Final = 75 - dato_array
print("La diferencia de velocidades entre un cheetah y los records olimpicos siendo el cheetah siempre más rápido es:", Final)

La diferencia de velocidades entre un cheetah y los records olimpicos siendo el cheetah siempre mayor es: [53.98305085 54.08153702 56.49637306 59.25813277 60.68986151 61.78064478
 62.11569322 62.29978093]
